# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  # Triggers the workflow on push to the default branch
  push:
    branches:
      - main   # Replace 'main' with your default branch if it's different
  # Allows the workflow to be manually triggered
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure compatibility with your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the static site
      - name: Build the site
        run: npm run build  # Make sure your project uses 'build' as the build command

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/github-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Directory where your built site is located

